language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: 1akiVRZc5Tvn6B79oYdhSACkwVSlnTlDDFjfWmYznbSsmVbu/XAD/8T+whMN4cHBDv+OkJkcWPBm/h8aaOHAL656aND0LqW/ioq9tKYGmTQyrZKiSredxtvkb5tfSQHqPcKSeDWb4/FQuAgdwa7hXNJDSMqTt6x2g87HFjvk9JWnsBwugPtMPB3VeQH8TaSgZ434PgZaQkPtFKamllPhXxqGL74ajP47bqGsl4hoGaBfUyW+BFRpJ8GIjhTTdKpGncKqqbfIDeWRc+f1woG8PjLTubWi25z0H+Clh80FwpvI7w042rCQwfSe5N0oe+zWcML9i1wmAuEqD6yK3WlML4SutGnHurwmpYtSyruDHFrnXZpcD7yXew/yQfZU0pqnlPAc89IcJrkWTKvMbdVs6u3SBTIOHnopV4Xltvbud6nwpFzRHVsvpMpv4JsYoTTl3ko3MBE8pY7ozXP/kWnixrIy/mr7ZoZtwCAe4FyTpeEP49Ngqv4hlSUawigl7ftUHkB9dHQl1tRKknUmS00LQg8Irf0jPS8rcB9UiZpN5tUwvIrZCcmjzgkI5WMZvaLKIcT1U0cno8A7TiiELZH0VvRlB218UAcJC+qkU42hOQYFRm2TgbSK2XfflpBOcbtYDPKXUUjFeYs9yb7S3MYjeS6oWR0qjNWYT5jKM9Oeen0=
    on:
      tags: true
      repo: higlass/higlass-bedlike-triangles-track
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: Vpb5PpRXE9ZIxwbD3hiFMiJKdoFVaV5eqdEQBaKLNP5Hz17mUs6F1CAfdfWPyoz1oWxjBwtkkaUcNFzBgL5Nkt7kNLwcFABYWf2GW+vYqhmze7hgi3xhDdk6hT3gPCcdG4MTfOCILatlASIwG7VhuNW7cFD7ohPJtvpbTn+zHkSfld/Pp7ZL5+Kt/D5BJ9lNhFRlTiuGagGUAoU/Xxfgn5UCnAlklhHYMSJrrilhc+9uf0ghCkYstsm5RN9yNdGHYbmQgX+n/k/Gd3zar65inJ6ioDnnLNmJ8Poc5IsWdy2eH/h00LTA39UEItgylrVO2nFCAo1Z/7zR6dM6Mqdcqdv9kK8TvdIvWfndPA1fjRWEqPeqvTbTA7H1hDhmnDQuCQXREALxozhaqFnIkKZnQCCbD/GHjJoqNbjWfa6/p6bJw8345qfjg8xpWjVpMXbcqzVBCAOZFoYs86PnmJfpgoTtVDPxUwKEa4xMf8nocUyBc1ETdjkoM9GQIHA7C5moThfjzEdu8xvghOY+s51XveuqnSW4C5ADC5jnOulq/qAqr9SjNOHGr7uo7x86lXc5TmXOCjsHyHhjvjTztU2glGBqIVXq4DE2xiai3V5pax649aer6QD2kNWf/PKXSUbGi7N9tswc/FwYYVgamCr0ENQTpVTQUO1C1aDp/TaTC0g=
    file: dist.zip
    on:
      repo: higlass/higlass-labelled-points-tracks
