language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: V0hcPJTA3iOq7G4w2JZqySHkMlBdNy+5D4FU7+P0Lwxaiw9Q/TKrCI5yOsCeAez21Gia+Cq4M6JkpsVyLDUfV20sIaks5BdvGaFlfL7gyWqyNIx2eA+QBkyly6vd3hkblUeE42fJLe/7tvtPJiFSICO8Ktof/fNvdp9DXhhFcJt9frCK6C6V1FYFDfV5sxGNQ9PzqxFlWoIKCISET8UiOPAAeeVWSi9g8SEPp9zNqNnrMnrQDLVsEdAnFCOK/3Mxac75dxmpkCX1g8Si0HvVRbsdnkv1njYUb2imeQOZoWH30IWGtRJGki9+frMHxBEdoUAs+r9jFkbRnTGlCDVzLO4R6mUlRmcVPI++BrsLWvpcKgDqXXZMkKNalvk4VNM9CSBsnPz0bY/++6VI90h5giBgXAbTZ9qdYhe6g9M0B+3ILrzqPDW+5oVuh/ICyn5GirlFojPSJQKzXBwYmvooYF+qfmoOGqyfXPLfY6JDI1jqk8mxjCGAqmmzlvBCFLvIes3i5pHBq8lwtEh/7LKCCqQpzY/ScnPULhWokaNgx7t94xFQGtW2yHp7obxRjVXBoU27Cukoafsg28mBMEibuFr07F2sSS8f3SHfzQBYv2v7Zo9OOX+s6/ZpFbSwvUBbPLhiiUWX7bRtlKrr01qgkt2QeDVdOS+/3cG8sTCC6tU=
    on:
      tags: true
      repo: pkerpedjiev/higlass-linear-labels-track
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: hCKQH/ickwzXBpnl/jyVd/8yc14N8rsmdMMlHOHH4Nspt2PhqhxYSVvMt9rLF4anHmp5HfgxWYxPsigDdhZqfY6j/k1LixpVP5LNp5nd3ESv88kW0m4uwVTU7Z8Ig3ucS65cFcONoDYPERGCPZVuJYGGwDiF6BnYOcWN/ah7WD6W7o/52TjevEemI6PfhzroEOUVYHOhxvfSShpWdzl4RkFVnV5SoAOPVaIRTCaXMcuivTYRv3/301lH7dtjRhGlo3lVhKX4M+vZBqQB0Nc8+mp239lLo03ybVUjDf5RCiNaEuOFuIWOjFQ9K+4w/62wy8eH+CRrCzlPHBw3WA5mtztB0uVBTD5yD8QWgrf9jdesREtpFk6dgldhbU4csCikN7qPTmwxW1q3F2/h3xUZd4O+ybmyXFek0iXTAWM3ACAfweTwyG/JFal/n0DduorzGcE2zEMwLzvyuG3H+F7+IwYppjfKFM4fKpbrr4SA7EyDtMn5EiFK46cqhH/Q0nA7bZPbtQ6jEx9ypjjYIhtqjwg8vqsBWe71c0I3hUL8Cd1pijXipW8HigVM29KzdYGXPBVt0dRP/rcsCx8Qm2yWczscuX7ekHa4GoLCt2cGBJv6OI0vv4nTrBxmYWydMrDUjte0whs3o6gCd5GK9rN+bwhqgx5W8Kd4ffCIkkJ3dwo=
    file: dist.zip
    on:
      repo: pkerpedjiev/higlass-linear-labels-track
